name: Main workflow

on: [push]

env:
  CACHE_IMAGE: davesnx/async_app
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Log in to docker hub
        run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
      - name: Build base from dockerfile
        run: |
          echo "run heroku"
